- clean up - moved functionality to libs - RHEL4 support

diff --git a/initscripts/rhel4/bootsr b/initscripts/rhel4/bootsr
--- a/initscripts/rhel4/bootsr
+++ b/initscripts/rhel4/bootsr
@@ -2,7 +2,7 @@
 #****h* comoonics-bootimage/bootsr
 #  NAME
 #    bootsr
-#    $Id: bootsr,v 1.6 2009-02-25 14:24:59 marc Exp $
+#    $Id: bootsr,v 1.7 2010-02-05 12:47:30 marc Exp $
 #  DESCRIPTION
 #    Comoonics Shared Root post boot settings
 #  AUTHOR
@@ -20,22 +20,26 @@
 # /etc/rc.d/init.d/bootsr
 #
 
-CCSD_OPTS=
-
 . /etc/init.d/functions
 
 BOOTIMAGE_PATH=/opt/atix/comoonics-bootimage
-CCSD_LOCK_FILE="/var/lock/subsys/ccsd-chroot"
-DEFAULT_LOCK_COUNT=50000
-CHROOT_PATH=$(/opt/atix/comoonics-bootimage/manage_chroot.sh -p) 
+CHROOT_PATH=$(${BOOTIMAGE_PATH}/manage_chroot.sh -p) 
 UPDATE_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a update"
 UMOUNT_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a umount"
 MOUNT_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a mount"
 MOUNT_CDSL="${BOOTIMAGE_PATH}/manage_chroot.sh -a mount_cdsl"
 CLEAN_START="${BOOTIMAGE_PATH}/manage_chroot.sh -a clean"
+PATCH_FILES="${BOOTIMAGE_PATH}/manage_chroot.sh -a patch_files"
+UNPATCH_FILES="${BOOTIMAGE_PATH}/manage_chroot.sh -a unpatch_files"
+CREATE_XFILES="${BOOTIMAGE_PATH}/manage_chroot.sh -a createxfiles"
 BUILD_FILE="/etc/comoonics-build.txt"
 
 RETVAL=0
+
+if [ -f /etc/sysconfig/comoonics-chroot ]; then
+	source /etc/sysconfig/comoonics-chroot
+fi
+
 . ${BOOTIMAGE_PATH}/boot-scripts/etc/std-lib.sh
 sourceLibs ${BOOTIMAGE_PATH}/boot-scripts
 sourceRootfsLibs ${BOOTIMAGE_PATH}/boot-scripts
@@ -86,8 +90,8 @@ function clean_start {
 #  SOURCE
 #
 function check_sharedroot {
-  root_fstype=$(mount | grep "/ " | awk 'BEGIN { exit_c=1; } { if ($5) { print $5; exit_c=0; } } END{ exit exit_c}')
-  if [ "$root_fstype" = "gfs" ]; then
+  local root_fstype=$1
+  if [ "$root_fstype" = "gfs" ] || [ "$root_fstype" = "ocfs2" ] || [ "$root_fstype" = "nfs" ] || [ "$root_fstype" = "glusterfs" ]; then
     return 1
   else
     return 0
@@ -123,33 +127,6 @@ function umount_chroot {
 }
 #************ get_runlevel
 
-#****f* bootsr/get_lockcount
-#  NAME
-#    get_getlockcount
-#  SYNOPSIS
-#    function get_lockcount default_lockcount
-#  MODIFICATION HISTORY
-#  IDEAS
-#  SOURCE
-#
-function get_lockcount {
-  DEF_LOCK_COUNT=$1
-  MAX_LCOK_COUNT=$2
-  [ -z "$DEF_LOCK_COUNT" ] && DEF_LOCK_COUNT=${DEFAULT_LOCK_COUNT}
-  [ -z "$DEF_LOCK_COUNT" ] && DEF_LOCK_COUNT=50000
-  [ -z "$MAX_LOCK_COUNT" ] && MAX_LOCK_COUNT=0
-  cat /proc/meminfo | grep MemTotal | awk -v maxlockcount=$MAX_LOCK_COUNT -v deflockcount=$DEF_LOCK_COUNT '
-  {
-  	lockcount=int($2/1024/512*deflockcount);
-  	if ((lockcount > maxlockcount) && (maxlockcount > 0))
-  	  lockcount=maxlockcount;
-  	print lockcount;
-  }
-'
-}
-#************ get_lockcount
-
-
 #****f* bootsr/main
 #  NAME
 #    main
@@ -175,67 +152,79 @@ clutype=$(repository_get_value clutype)
 case "$1" in
   start)
   	# will do
-  	# - activate all lvm devices (na)
-  	# - activate swap partitions (currently disabled)
-  	# - mount everything except nfs (na)
-  	# - adjust dlm lock_count
   	# - update chroot environment for additional services (fence_ack_server)
-
-    if [ check_sharedroot ]; then
-      
-#      runlevel=$(get_runlevel)
-      echo  "Doing the Comoonics Shared Root post settings "
+    
+  	# first clean old repos
+    check_mtab $rootfs
+    
+    check_sharedroot $rootfs
+    sharedroot=$?
+    if  [ -n "$rootfs" ] && [ $sharedroot ]; then
       touch /var/lock/subsys/bootsr
-      mkdir -p /var/run/cluster
-      for file in ccsd.pid ccsd.sock; do
-            ln -s $(/opt/atix/comoonics-bootimage/manage_chroot.sh -p)/var/run/cluster/$file /var/run/cluster
-      done
-      
-#      echo `date` Doing the Comoonics Shared Root post settings | tee -a /var/log/bootsr | logger -t com-bootsr
-#      /sbin/lvm vgscan --ignorelockingfailure --mknodes 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-#      /sbin/lvm vgchange --ignorelockingfailure -ay 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-#      sleep 1
-#      /sbin/swapon -av 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-      /bin/mount -at gfs 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-      count=$(get_lockcount ${DEFAULT_LOCK_COUNT} ${MAX_LOCK_COUNT})
-	  action "Changing dlm:drop_count to $count" "sh -c \"echo $count > /proc/cluster/lock_dlm/drop_count\""
-#      echo $count > /proc/cluster/lock_dlm/drop_count && echo -n "($count)" &&
-#      success || failure
-#      echo
-
-      # Start ccsd-chroot if it will not be started from init in Runlevel 3
-      # FIXME: There will be propably be no $FENCE_CHROOT this time.
-#      chkconfig --list ccsd-chroot | grep "3:on" >/dev/null 2>/dev/null
-#      if [ $? -eq 1 ] && [ ! -e /var/run/cluster/ccsd.pid ]; then
-#         /etc/init.d/ccsd-chroot start
-#      fi
-	  # Update chroot environment with files from /etc/comoonics/bootimage-chroot
-	  action "Updating chroot environment" $UPDATE_CHROOT
- 	  action "Mounting filesystems to chroot" $MOUNT_CHROOT
+      if [ -z "$chrootneeded" ]; then
+        clusterfs_chroot_needed init
+        __default=$?
+        chrootneeded=$(getParameter chroot $__default)
+      fi
+	  if [ $chrootneeded -eq 0 ]; then
+ 	  	action "Mounting filesystems to chroot" $MOUNT_CHROOT
+	  	action "Updating chroot environment" $UPDATE_CHROOT
+  	  fi 
  	  
+   	  typeset -f cc_init >/dev/null && action "Starting ${clutype} dependent services" cc_init start "$CHROOT_PATH" "$rootfs"
+ 	  if [ "${clutype}" != "${rootfs}" ]; then
+ 	   	typeset -f clusterfs_init >/dev/null && action "Starting ${rootfs} dependent services" clusterfs_init start "$CHROOT_PATH" "$rootfs"
+ 	  fi
     fi
     ;;
   stop)
+ 	  typeset -f cc_init >/dev/null && action "Stopping ${clutype} dependent services" cc_init stop "$CHROOT_PATH" "$rootfs"
+ 	  if [ "${clutype}" != "${rootfs}" ]; then
+   	    typeset -f clusterfs_init >/dev/null && action "Stopping ${rootfs} dependent services" clusterfs_init stop "$CHROOT_PATH" "$rootfs"
+ 	  fi 
   	  [ -e /var/lock/subsys/bootsr ] && rm -f /var/lock/subsys/bootsr 
-	  action "Cleaning up chroot environment" $UMOUNT_CHROOT
+	  typeset -f ${rootfs}_needed >/dev/null && ${rootfs}_chroot_needed init
+	  if [ $? -eq 0 ]; then
+	    action "Cleaning up chroot environment" $UMOUNT_CHROOT
+	  fi
+  	  $PATCH_FILES
+  	  $CREATE_XFILES
         ;;
   status)
       exit 0
       ;;
-  restart|reload)
+  reload)
       if [ check_sharedroot ]; then
-	    action "Updating chroot environment" $UPDATE_CHROOT
+  	    typeset -f ${rootfs}_needed >/dev/null && ${rootfs}_chroot_needed init
+	    if [ $? -eq 0 ]; then
+	      action "Updating chroot environment" $UPDATE_CHROOT
+	    fi
 	  fi
+	  ;;
+  restart)
+  	 $0 stop
+  	 $0 start 
+      ;;
+  patch_files)
+      $PATCH_FILES
+      ;;
+  unpatch_files)
+      $UNPATCH_FILES
       ;;
   *)
-      echo "Usage: bootsr {start|stop|status|restart|reload}"
-      exit 1
+        echo "Usage: bootsr {start|stop|status|restart|reload}"
+        exit 1
 esac
 exit $RETVAL
 #************ main
 ###############
 # $Log: bootsr,v $
-# Revision 1.6  2009-02-25 14:24:59  marc
+# Revision 1.7  2010-02-05 12:47:30  marc
+# - clean up
+# - moved functionality to libs
+# - RHEL4 support
+#
+# Revision 1.6  2009/02/25 14:24:59  marc
 # backport of new features to rhel4
 #
 # Revision 1.5  2008/10/29 14:45:33  mark
diff --git a/initscripts/rhel5/bootsr b/initscripts/rhel5/bootsr
--- a/initscripts/rhel5/bootsr
+++ b/initscripts/rhel5/bootsr
@@ -2,7 +2,7 @@
 #****h* comoonics-bootimage/bootsr
 #  NAME
 #    bootsr
-#    $Id: bootsr,v 1.22 2009-04-20 07:18:08 marc Exp $
+#    $Id: bootsr,v 1.23 2010-02-05 12:47:30 marc Exp $
 #  DESCRIPTION
 #    Comoonics Shared Root post boot settings
 #  AUTHOR
@@ -20,14 +20,10 @@
 # /etc/rc.d/init.d/bootsr
 #
 
-CCSD_OPTS=
-
 . /etc/init.d/functions
 
 BOOTIMAGE_PATH=/opt/atix/comoonics-bootimage
-CCSD_LOCK_FILE="/var/lock/subsys/ccsd-chroot"
-DEFAULT_LOCK_COUNT=50000
-CHROOT_PATH=$(/opt/atix/comoonics-bootimage/manage_chroot.sh -p) 
+CHROOT_PATH=$(${BOOTIMAGE_PATH}/manage_chroot.sh -p) 
 UPDATE_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a update"
 UMOUNT_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a umount"
 MOUNT_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a mount"
@@ -37,7 +33,6 @@ PATCH_FILES="${BOOTIMAGE_PATH}/manage_chroot.sh -a patch_files"
 UNPATCH_FILES="${BOOTIMAGE_PATH}/manage_chroot.sh -a unpatch_files"
 CREATE_XFILES="${BOOTIMAGE_PATH}/manage_chroot.sh -a createxfiles"
 BUILD_FILE="/etc/comoonics-build.txt"
-VAR_RUN_FILES="cman_admin cman_client"
 
 RETVAL=0
 
@@ -132,33 +127,6 @@ function umount_chroot {
 }
 #************ get_runlevel
 
-#****f* bootsr/get_lockcount
-#  NAME
-#    get_getlockcount
-#  SYNOPSIS
-#    function get_lockcount default_lockcount
-#  MODIFICATION HISTORY
-#  IDEAS
-#  SOURCE
-#
-function get_lockcount {
-  DEF_LOCK_COUNT=$1
-  MAX_LCOK_COUNT=$2
-  [ -z "$DEF_LOCK_COUNT" ] && DEF_LOCK_COUNT=${DEFAULT_LOCK_COUNT}
-  [ -z "$DEF_LOCK_COUNT" ] && DEF_LOCK_COUNT=50000
-  [ -z "$MAX_LOCK_COUNT" ] && MAX_LOCK_COUNT=0
-  cat /proc/meminfo | grep MemTotal | awk -v maxlockcount=$MAX_LOCK_COUNT -v deflockcount=$DEF_LOCK_COUNT '
-  {
-  	lockcount=int($2/1024/512*deflockcount);
-  	if ((lockcount > maxlockcount) && (maxlockcount > 0))
-  	  lockcount=maxlockcount;
-  	print lockcount;
-  }
-'
-}
-#************ get_lockcount
-
-
 #****f* bootsr/main
 #  NAME
 #    main
@@ -184,56 +152,31 @@ clutype=$(repository_get_value clutype)
 case "$1" in
   start)
   	# will do
-  	# - activate swap partitions (currently disabled)
-  	# - mount everything except nfs (na)
   	# - update chroot environment for additional services (fence_ack_server)
     
   	# first clean old repos
     check_mtab $rootfs
     
-    check_sharedroot $rootfs
-    sharedroot=$?
-    if  [ -n "$rootfs" ] && [ $sharedroot ]; then
-#      runlevel=$(get_runlevel)
-      touch /var/lock/subsys/bootsr
-#      echo `date` Doing the Comoonics Shared Root post settings | tee -a /var/log/bootsr | logger -t com-bootsr
-#      /sbin/swapon -av 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-      if [ "$rootfs" = "gfs" ]; then
-        echo  -n "Doing the Comoonics Shared Root post settings "
-        /bin/mount -at $rootfs 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-	    # Create symbolic links
-	    for file in ${VAR_RUN_FILES}; do
-	  	  [ -e /var/run/${file} ] && rm -f /var/run/${file}
-	  	  test -e ${CHROOT_PATH}/var/run/${file} && /bin/ln -sf ${CHROOT_PATH}/var/run/${file} /var/run/
-        done
-        mkdir -p /var/run/cluster
-        for file in ccsd.pid ccsd.sock; do
-            ln -s ${CHROOT_PATH}/var/run/cluster/$file /var/run/cluster
-        done
-        success
-      fi
-      
-	  # Update chroot environment with files from /etc/comoonics/bootimage-chroot
-      if [ -z "$chrootneeded" ]; then
-        clusterfs_chroot_needed init
-        __default=$?
-        chrootneeded=$(getParameter chroot $__default)
-      fi
-	  if [ $chrootneeded -eq 0 ]; then
- 	  	action "Mounting filesystems to chroot" $MOUNT_CHROOT
-	  	action "Updating chroot environment" $UPDATE_CHROOT
-  	  fi 
+    touch /var/lock/subsys/bootsr
+    if [ -z "$chrootneeded" ]; then
+      clusterfs_chroot_needed init
+      __default=$?
+      chrootneeded=$(getParameter chroot $__default)
+    fi
+    if [ $chrootneeded -eq 0 ]; then
+       action "Mounting filesystems to chroot" $MOUNT_CHROOT
+       action "Updating chroot environment" $UPDATE_CHROOT
+    fi 
  	  
-   	  typeset -f cc_init >/dev/null && action "Starting ${clutype} dependent services" cc_init start
- 	  if [ "${clutype}" != "${rootfs}" ]; then
- 	   	typeset -f clusterfs_init >/dev/null && action "Starting ${rootfs} dependent services" clusterfs_init start
- 	  fi
+    typeset -f cc_init >/dev/null && action "Starting ${clutype} dependent services" cc_init start "$CHROOT_PATH" "$clutype"
+    if [ "${clutype}" != "${rootfs}" ]; then
+       typeset -f clusterfs_init >/dev/null && action "Starting ${clutype} dependent services" "$CHROOT_PATH" "$clutype"
     fi
     ;;
   stop)
- 	  typeset -f cc_init >/dev/null && action "Stopping ${clutype} dependent services" cc_init stop
+ 	  typeset -f cc_init >/dev/null && action "Stopping ${clutype} dependent services" cc_init stop "$CHROOT_PATH" "$clutype"
  	  if [ "${clutype}" != "${rootfs}" ]; then
-   	    typeset -f clusterfs_init >/dev/null && action "Stopping ${rootfs} dependent services" clusterfs_init stop
+   	    typeset -f clusterfs_init >/dev/null && action "Stopping ${rootfs} dependent services" clusterfs_init stop "$CHROOT_PATH" "$rootfs"
  	  fi 
   	  [ -e /var/lock/subsys/bootsr ] && rm -f /var/lock/subsys/bootsr 
 	  typeset -f ${rootfs}_needed >/dev/null && ${rootfs}_chroot_needed init
@@ -272,7 +215,12 @@ exit $RETVAL
 #************ main
 ###############
 # $Log: bootsr,v $
-# Revision 1.22  2009-04-20 07:18:08  marc
+# Revision 1.23  2010-02-05 12:47:30  marc
+# - clean up
+# - moved functionality to libs
+# - RHEL4 support
+#
+# Revision 1.22  2009/04/20 07:18:08  marc
 # - got that xfiles and patching right
 #
 # Revision 1.21  2009/04/14 15:26:54  marc
