adapted to support bootimage 1.3

diff --git a/bootsr b/bootsr
--- a/bootsr
+++ b/bootsr
@@ -2,7 +2,7 @@
 #****h* comoonics-bootimage/bootsr
 #  NAME
 #    bootsr
-#    $Id: bootsr,v 1.11 2007-02-09 11:11:42 marc Exp $
+#    $Id: bootsr,v 1.12 2007-08-06 16:01:43 mark Exp $
 #  DESCRIPTION
 #    Comoonics Shared Root post boot settings
 #  AUTHOR
@@ -24,11 +24,11 @@ CCSD_OPTS=
 
 . /etc/init.d/functions
 
-CCSD_LOCK_FILE="/var/lock/subsys/ccsd"
+CCSD_LOCK_FILE="/var/lock/subsys/ccsd-chroot"
 DEFAULT_LOCK_COUNT=50000
-FENCE_CHROOT=/var/lib/fence_tool
-FENCE_CHROOT_INITRD=/var/lib/fence_tool
-MKSERVICE_FOR_INITRD="/opt/atix/comoonics-bootimage/mkservice_for_initrd.sh"
+UPDATE_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a update"
+UMOUNT_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a umount"
+MOUNT_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a mount"
 BUILD_FILE="/etc/comoonics-build.txt"
 
 RETVAL=0
@@ -66,6 +66,21 @@ function get_runlevel {
 }
 #************ get_runlevel
 
+#************ umount_chroot
+#****f* bootsr/umount_chroot
+#  NAME
+#    umount_chroot
+#  SYNOPSIS
+#    function umount_chroot
+#  MODIFICATION HISTORY
+#  IDEAS
+#  SOURCE
+#
+function umount_chroot {
+  return $(runlevel | cut -d" " -f2)
+}
+#************ get_runlevel
+
 #****f* bootsr/get_lockcount
 #  NAME
 #    get_getlockcount
@@ -92,57 +107,6 @@ function get_lockcount {
 }
 #************ get_lockcount
 
-#******f* bootsr/prebuild_fenced_chroot
-#  NAME
-#    prebuild_fenced_chroot
-#  SYNOPSIS
-#    prebuild_fenced_chroot FENCE_CHROOT FENCE_CHROOT_INITRD FENCE_CHROOT_SOURCE FENCE_CHROOT_ARCHIVE
-#  SOURCE
-#
-function prebuild_fenced_chroot {
-  local FENCE_CHROOT=$1
-  local FENCE_CHROOT_INITRD=$2
-  local FENCE_CHROOT_SOURCE=$3
-  local FENCE_CHROOT_ARCHIVE=$4
-
-  [ ! -d $FENCE_CHROOT ] && mkdir -p ${FENCE_CHROOT}
-  # check if $FENCE_CHROOT is mounted or it's located on an no stat "UNKOWN" fstype
-  mount | grep "${FENCE_CHROOT}" &>/dev/null || stat -f -c "%T" ${FENCE_CHROOT} | grep -v "^UNKNOWN" &>/dev/null
-  if [ $? -ne 0 ] ; then
-    mount -t tmpfs none $FENCE_CHROOT
-  fi
-#  if [ "${FENCE_CHROOT}" != "${FENCE_CHROOT_INITRD}" ]; then
-#  	files1=$(find ${FENCE_CHROOT} -type f 2>/dev/null | wc -l)
-#  	files2=$(find ${FENCE_CHROOT_INITRD} -type f 2>/dev/null | wc -l)
-#  	if [ $files1 -lt $files2 ]; then
-#  		copy=1
-#  	fi
-#  fi
-#  if [ "${FENCE_CHROOT}" != "${FENCE_CHROOT_SOURCE}" ]; then
-#  	files1=$(find ${FENCE_CHROOT} -type f 2>/dev/null | wc -l)
-#  	files2=$(find ${FENCE_CHROOT_SOURCE} -type f 2>/dev/null | wc -l)
-#  	if [ $files1 -lt $files2 ]; then
-#  		copy=1
-#  	fi
-#  fi
-
-#  if [ -n "$copy" ] && [ $copy -eq 1 ]; then
-	# Copy all files into FENCE_CHROOT
-	# FIXME: Why do we need FENCE_CHROOT_SOURCE and FENCE_CHROOT_INITRD for this ?
-	if [ -d ${FENCE_CHROOT_SOURCE} ]; then
-#       ${MKSERVICE_FOR_INITRD} $FENCE_CHROOT /sbin/ccsd nostart &>/dev/null
-       ${MKSERVICE_FOR_INITRD} $FENCE_CHROOT /sbin/fenced nostart &>/dev/null
-	elif [ -d ${FENCE_CHROOT_INITRD} ] && [ "${FENCE_CHROOT_INITRD}" != "${FENCE_CHROOT}" ]; then
-#       ${MKSERVICE_FOR_INITRD} $FENCE_CHROOT /sbin/ccsd nostart &>/dev/null
-       ${MKSERVICE_FOR_INITRD} $FENCE_CHROOT /sbin/fenced nostart &>/dev/null
-	elif [ -z ${FENCE_CHROOT_TAR} ] && [ -e ${FENCE_CHROOT_ARCHIVE} ]; then
-		pushd ${FENCE_CHROOT} &>/dev/null
-		tar xvzf ${FENCE_CHROOT_ARCHIVE}
-		popd &>/dev/null
-    fi
-#  fi
-}
-#************* prebuild_fenced_chroot
 
 #****f* bootsr/main
 #  NAME
@@ -158,85 +122,44 @@ function prebuild_fenced_chroot {
 case "$1" in
   start)
   	# will do
-  	# - activate all lvm devices
+  	# - activate all lvm devices (na)
   	# - activate swap partitions (currently disabled)
-  	# - mount everything except nfs
-  	#   FIXME: Do we really want to do this ?
+  	# - mount everything except nfs (na)
   	# - adjust dlm lock_count
-  	# - prepare chroot environment for cluster services (ccsd, fenced)
+  	# - update chroot environment for additional services (fence_ack_server)
 
     if [ check_sharedroot ]; then
-      runlevel=$(get_runlevel)
-      echo -n "Doing the Comoonics Shared Root post settings "
-      echo `date` Doing the Comoonics Shared Root post settings | tee -a /var/log/bootsr | logger -t com-bootsr
-      /sbin/lvm vgscan --ignorelockingfailure --mknodes 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-      /sbin/lvm vgchange --ignorelockingfailure -ay 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-      sleep 1
+      
+#      runlevel=$(get_runlevel)
+      echo  "Doing the Comoonics Shared Root post settings "
+      touch /var/lock/subsys/bootsr
+#      echo `date` Doing the Comoonics Shared Root post settings | tee -a /var/log/bootsr | logger -t com-bootsr
+#      /sbin/lvm vgscan --ignorelockingfailure --mknodes 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
+#      /sbin/lvm vgchange --ignorelockingfailure -ay 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
+#      sleep 1
 #      /sbin/swapon -av 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-      /bin/mount -at nonfs 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
+#      /bin/mount -at nonfs 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
       count=$(get_lockcount ${DEFAULT_LOCK_COUNT} ${MAX_LOCK_COUNT})
-      echo $count > /proc/cluster/lock_dlm/drop_count && echo -n "($count)" &&
-      success || failure
-      echo
+	  action "Changing dlm:drop_count to $count" "sh -c \"echo $count > /proc/cluster/lock_dlm/drop_count\""
+#      echo $count > /proc/cluster/lock_dlm/drop_count && echo -n "($count)" &&
+#      success || failure
+#      echo
 
-      if [ -e /initrd/var/run/cluster/ccsd.pid ]; then
-        echo -n "Stopping ccsd from initrd"
-        kill $(cat  /initrd/var/run/cluster/ccsd.pid) &&
-        rm -f /initrd/var/run/cluster/ccsd.pid
-        if [ $? -eq 0 ]; then
-          success
-        else
-          failure
-        fi
-        echo
-      fi
       # Start ccsd-chroot if it will not be started from init in Runlevel 3
       # FIXME: There will be propably be no $FENCE_CHROOT this time.
-      chkconfig --list ccsd-chroot | grep "3:on" >/dev/null 2>/dev/null
-      if [ $? -eq 1 ] && [ ! -e /var/run/cluster/ccsd.pid ]; then
-         /etc/init.d/ccsd-chroot start
-      fi
-	  echo -n "Prebuilding fenced chroot"
-	  #if [ -d ${FENCE_CHROOT} ]; then
-	  #  mv ${FENCE_CHROOT} ${FENCE_CHROOT}.bak
-      #fi
-	  if [ -z "$BUILD_FILE" ] || [ ! -e $FENCE_CHROOT/$BUILD_FILE ] ||
-	     [ ! -e $FENCE_CHROOT_INITRD/$BUILD_FILE ] || [ $FENCE_CHROOT/$BUILD_FILE -ot $FENCE_CHROOT_INITRD/$BUILD_FILE ]; then
-	    prebuild_fenced_chroot $FENCE_CHROOT $FENCE_CHROOT_INITRD $FENCE_CHROOT_SOURCE $FENCE_CHROOT_ARCHIVE
-        if [ $? -eq 0 ]; then
-          success
-        else
-          failure
-        fi
-        echo
-	  fi
+#      chkconfig --list ccsd-chroot | grep "3:on" >/dev/null 2>/dev/null
+#      if [ $? -eq 1 ] && [ ! -e /var/run/cluster/ccsd.pid ]; then
+#         /etc/init.d/ccsd-chroot start
+#      fi
+	  # Update chroot environment with files from /etc/comoonics/bootimage-chroot
+	  action "Updating chroot environment" $UPDATE_CHROOT
+ 	  action "Mounting filesystems to chroot" $MOUNT_CHROOT
+ 	  
     fi
     ;;
   stop)
-      chkconfig --list ccsd | grep "3:on" >/dev/null 2>/dev/null
-      if [ $? -eq 1 ]; then
-        echo -n "Stopping ccsd:"
-        for sec in $(seq 1 10)
-        do
-          if pidof ccsd > /dev/null
-            then
-             # get the pid of ccsd from /var/run/cluster/ccsd.pid
-             # and break if the file is not there
-             [ -r /var/run/cluster/ccsd.pid ] || break
-             pid=$(cat /var/run/cluster/ccsd.pid )
-             kill $pid 2> /dev/null || break
-             sleep 1
-          else
-             success "shutdown"
-	         rm /var/run/cluster/ccsd.pid
-             echo
-             exit 0
-          fi
-        done
-        failure "shutdown"
-        echo
-        exit 1
-      fi
+  	  [ -e /var/lock/subsys/bootsr ] && rm -f /var/lock/subsys/bootsr 
+	  action "Cleaning up chroot environment" $UMOUNT_CHROOT
         ;;
   status)
       exit 0
@@ -261,7 +184,10 @@ exit $RETVAL
 #************ main
 ###############
 # $Log: bootsr,v $
-# Revision 1.11  2007-02-09 11:11:42  marc
+# Revision 1.12  2007-08-06 16:01:43  mark
+# adapted to support bootimage 1.3
+#
+# Revision 1.11  2007/02/09 11:11:42  marc
 # added definition for Builddatefile (obsolete???)
 #
 # Revision 1.10  2006/12/04 17:37:01  marc
