moved creation of chroot to bootsr

diff --git a/fenced-chroot b/fenced-chroot
--- a/fenced-chroot
+++ b/fenced-chroot
@@ -84,7 +84,7 @@ start()
 #      failure
 #    fi
 #  el
-  if [ -e ${INITRD_DIR}${FENCE_CHROOT_INITRD}/var/run/fenced.pid ]; then
+  if [ -e ${INITRD_DIR}${FENCE_CHROOT_INITRD}/var/run/fenced.pid ] && [ ! -e /FAILURE_fenced ]; then
     echo -n $"Stopping fenced from initrd"
     kill $(cat ${INITRD_DIR}${FENCE_CHROOT_INITRD}/var/run/fenced.pid) &&
     rm -f ${INITRD_DIR}${FENCE_CHROOT_INITRD}/var/run/fenced.pid
@@ -93,23 +93,20 @@ start()
     else
       failure
     fi
-    copy=1
   fi
 
-  if [ "${FENCE_CHROOT}" != "${FENCE_CHROOT_INITRD}" ]; then
-  	files1=$(find ${FENCE_CHROOT} -type f 2>/dev/null | wc -l)
-  	files2=$(find ${FENCE_CHROOT_INITRD} -type f 2>/dev/null | wc -l)
-  	if [ $files1 -lt $files2 ]; then
-  		copy=1
-  	fi
-  fi
-
-  if [ -e ${FENCE_CHROOT_INITRD}/var/run/fenced.pid ]; then
-  	[ "${FENCE_CHROOT_INITRD}" != "${FENCE_CHROOT}" ] && copy=1
+  if [ -e ${FENCE_CHROOT_INITRD}/var/run/fenced.pid ] && [ ! -e /cdsl.local/FAILURE_fenced ]; then
     stop
   fi
 
   echo -n "Starting fence domain (chroot):"
+  if [ -e /cdsl.local/FAILURE_fenced ]; then
+  	passed
+  	echo
+  	echo "Leaving as errors detected before"
+  	rm -f /cdsl.local/FAILURE_fenced
+  	exit 1
+  fi
 
   # If gulm is in ccs, don't start fenced
   if ! [ -r /etc/cluster/cluster.conf ]
@@ -134,23 +131,6 @@ start()
     echo
     return 0
   fi
-  [ ! -d $FENCE_CHROOT ] && mkdir -p ${FENCE_CHROOT}
-  mount | grep "${FENCE_CHROOT}" &>/dev/null || stat -f -c "%T" ${FENCE_CHROOT} | grep -v "^UNKNOWN" &>/dev/null
-  if [ $? -ne 0 ] ; then
-    mount -t tmpfs none $FENCE_CHROOT
-    copy=1
-  fi
-  if [ -n "$copy" ] && [ $copy -eq 1 ]; then
-	if [ -d ${FENCE_CHROOT_SOURCE} ]; then
-		cp -a $FENCE_CHROOT_SOURCE/* $FENCE_CHROOT/
-	elif [ -d ${FENCE_CHROOT_INITRD} ] && [ "${FENCE_CHROOT_INITRD}" != "${FENCE_CHROOT}" ]; then
-		cp -a $FENCE_CHROOT_INITRD/* $FENCE_CHROOT/
-	elif [ -z ${FENCE_CHROOT_TAR} ] && [ -e ${FENCE_CHROOT_TAR} ]; then
-		pushd
-		cd ${FENCE_CHROOT}; tar xvzf ${FENCE_CHROOT_TAR}
-		popd
-	fi
-  fi &&
   [ -e $FENCE_CHROOT/var/run/fenced.pid ] && rm -r $FENCE_CHROOT/var/run/fenced.pid
   chroot $FENCE_CHROOT fenced ${FENCE_OPTS} > /dev/null 2>&1
   rtrn=$?
@@ -287,7 +267,10 @@ exit $rtrn
 
 #########################
 # $Log: fenced-chroot,v $
-# Revision 1.9  2006-08-14 17:43:03  marc
+# Revision 1.10  2006-08-28 16:02:22  marc
+# moved creation of chroot to bootsr
+#
+# Revision 1.9  2006/08/14 17:43:03  marc
 # bugfixes with FENCE_CHROOT and FENCE_CHROOT_SOURCE
 #
 # Revision 1.8  2006/08/02 12:26:23  marc
