- rewrote files to be more filesystem independent

diff --git a/initscripts/rhel5/bootsr b/initscripts/rhel5/bootsr
--- a/initscripts/rhel5/bootsr
+++ b/initscripts/rhel5/bootsr
@@ -2,7 +2,7 @@
 #****h* comoonics-bootimage/bootsr
 #  NAME
 #    bootsr
-#    $Id: bootsr,v 1.6 2007-11-22 16:31:35 mark Exp $
+#    $Id: bootsr,v 1.7 2008-06-10 10:00:37 marc Exp $
 #  DESCRIPTION
 #    Comoonics Shared Root post boot settings
 #  AUTHOR
@@ -24,12 +24,13 @@ CCSD_OPTS=
 
 . /etc/init.d/functions
 
+BOOTIMAGE_PATH=/opt/atix/comoonics-bootimage
 CCSD_LOCK_FILE="/var/lock/subsys/ccsd-chroot"
 DEFAULT_LOCK_COUNT=50000
 CHROOT_PATH=$(/opt/atix/comoonics-bootimage/manage_chroot.sh -p) 
-UPDATE_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a update"
-UMOUNT_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a umount"
-MOUNT_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a mount"
+UPDATE_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a update"
+UMOUNT_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a umount"
+MOUNT_CHROOT="${BOOTIMAGE_PATH}/manage_chroot.sh -a mount"
 BUILD_FILE="/etc/comoonics-build.txt"
 VAR_RUN_FILES="cman_admin cman_client"
 
@@ -46,8 +47,8 @@ RETVAL=0
 #  SOURCE
 #
 function check_sharedroot {
-  root_fstype=$(mount | grep "/ " | awk 'BEGIN { exit_c=1; } { if ($5) { print $5; exit_c=0; } } END{ exit exit_c}')
-  if [ "$root_fstype" = "gfs" ]; then
+  root_fstype=$1
+  if [ "$root_fstype" = "gfs" ] || [ "$root_fstype" = "ocfs2" ]; then
     return 1
   else
     return 0
@@ -137,6 +138,37 @@ function get_lockcount {
 #  IDEAS
 #  SOURCE
 #
+logfile=/var/log/bootsr.log
+
+#to be backward compatible
+exec 3>> $logfile
+exec 4>> $logfile
+exec 5>> $logfile
+exec 6>> $logfile
+exec 7>> $logfile
+
+. ${BOOTIMAGE_PATH}/boot-scripts/etc/boot-lib.sh
+. ${BOOTIMAGE_PATH}/boot-scripts/etc/chroot-lib.sh
+. ${BOOTIMAGE_PATH}/boot-scripts/etc/stdfs-lib.sh
+. ${BOOTIMAGE_PATH}/boot-scripts/etc/std-lib.sh
+. ${BOOTIMAGE_PATH}/boot-scripts/etc/defaults.sh
+. ${BOOTIMAGE_PATH}/boot-scripts/etc/clusterfs-lib.sh
+
+distribution=$(getDistribution)
+clutype=$(getCluType)
+rootfs=$(get_mounted_rootfs)
+
+if ! [ -e ${BOOTIMAGE_PATH}/boot-scripts/etc/$clutype-lib.sh ]; then
+  echo "Cannot find ${BOOTIMAGE_PATH}/etc/$clutype-lib.sh"
+  exit 1
+fi
+. ${BOOTIMAGE_PATH}/boot-scripts/etc/$clutype-lib.sh
+
+if ! [ -e ${BOOTIMAGE_PATH}/boot-scripts/etc/$rootfs-lib.sh ]; then
+  echo "Cannot find ${BOOTIMAGE_PATH}/boot-scripts/etc/$rootfs-lib.sh"
+  exit 1
+fi
+. ${BOOTIMAGE_PATH}/boot-scripts/etc/$rootfs-lib.sh
 
 # See how we were called.
 case "$1" in
@@ -145,15 +177,16 @@ case "$1" in
   	# - activate swap partitions (currently disabled)
   	# - mount everything except nfs (na)
   	# - update chroot environment for additional services (fence_ack_server)
-
-    if [ check_sharedroot ]; then
-      
+    
+    check_sharedroot $rootfs
+    sharedroot=$?
+    if  [ -n "$rootfs" ] && [ $sharedroot ]; then
 #      runlevel=$(get_runlevel)
       echo  "Doing the Comoonics Shared Root post settings "
       touch /var/lock/subsys/bootsr
 #      echo `date` Doing the Comoonics Shared Root post settings | tee -a /var/log/bootsr | logger -t com-bootsr
 #      /sbin/swapon -av 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
-      /bin/mount -at gfs 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
+      /bin/mount -at $rootfs 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
 	  # Create symbolic links
 	  for file in $VAR_RUN_FILES; do
 	  	/bin/ln -sf $CHROOT_PATH/var/run/$file /var/run/
@@ -168,9 +201,17 @@ case "$1" in
 	  action "Updating chroot environment" $UPDATE_CHROOT
  	  action "Mounting filesystems to chroot" $MOUNT_CHROOT
  	  
+ 	  action "Starting ${clutype}dependent services" ${clutype}_init start
+ 	  if [ "${clutype}" != "${rootfs}" ]; then
+ 	    action "Starting ${rootfs}dependent services" ${rootfs}_init start
+ 	  fi 
     fi
     ;;
   stop)
+ 	  action "Stopping ${clutype}dependent services" ${clutype}_init stop
+ 	  if [ "${clutype}" != "${rootfs}" ]; then
+   	    action "Stopping ${rootfs}dependent services" ${rootfs}_init stop
+ 	  fi 
   	  [ -e /var/lock/subsys/bootsr ] && rm -f /var/lock/subsys/bootsr 
 	  action "Cleaning up chroot environment" $UMOUNT_CHROOT
 	  patch_halt
@@ -190,7 +231,10 @@ exit $RETVAL
 #************ main
 ###############
 # $Log: bootsr,v $
-# Revision 1.6  2007-11-22 16:31:35  mark
+# Revision 1.7  2008-06-10 10:00:37  marc
+# - rewrote files to be more filesystem independent
+#
+# Revision 1.6  2007/11/22 16:31:35  mark
 # added automatic mount for gfs filesystems, fixes bz #150
 #
 # Revision 1.5  2007/10/05 13:38:09  mark
